version: "3.7"

services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: 5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8090:8080

  keycloak:
    image: keycloak
    container_name: keycloak
    build: ./qa-portal-infra
    depends_on:
      - database
    environment:
      - DB_VENDOR=postgres
      - DB_ADDR=database
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=postgres
      - DB_PASSWORD=postgres
